version: "3.8"

networks:
  proxy:
    name: proxy

volumes:
  mysql-data:
    driver: local
services:
  mysql:
    image: mysql:latest
    networks:
      - proxy
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=emobility_charging
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SHOW databases'"
      interval: 10s
      retries: 3
  api:
    build: ./backend
    networks:
      - proxy
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
  # app:
  #   build: ./frontend
  #   networks:
  #     - proxy
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - api


