export const GET_RECORDS_PENDING = "GET_RECORDS_PENDING";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export const GET_RECORDS_FAILED = "GET_RECORDS_FAILED";

export const FILTER_RECORDS = "FILTER_RECORDS";